name: Build & Publish Snapshots (YoStar upstream)

on:
  schedule:
    - cron: '0 18 * * *'   # 03:00 JST
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Fetch YoStar JP data (sparse)
        run: |
          git clone --depth=1 --filter=blob:none https://github.com/Kengxxiao/ArknightsGameData_YoStar.git tmp_repo
          cd tmp_repo
          git sparse-checkout init --cone
          git sparse-checkout set             ja_JP/gamedata/excel             ja_JP/gamedata/story             ja_JP/dyn/gamedata/excel             ja_JP/dyn/gamedata/story
          ls -R ja_JP | head -n 50

      - name: Build snapshots from upstream JP
        run: |
          python scripts/extract.py --source ./tmp_repo/ja_JP --out ./docs
          test -f ./docs/latest/index.json || (echo "index.json not generated" && exit 1)
          echo "Top of docs:"; ls -R ./docs | head -n 200

      - name: List stories (debug)
        run: |
          test -d ./docs/latest/stories && ls ./docs/latest/stories | head -n 50 || echo "no stories dir"


      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
