name: Build & Deploy (Pages)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # 入力元（今回の修正点）
      EXCEL_SRC: gamedata/excel
      STORY_SRC: gamedata/story
      # 出力先
      OUT_DIR: docs
      # .txt も JSON として配信したい場合は true（任意）
      STORY_JSON_WRAPPER: "true"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (if any)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build site
        run: |
          python scripts/extract.py
        env:
          EXCEL_SRC: ${{ env.EXCEL_SRC }}
          STORY_SRC: ${{ env.STORY_SRC }}
          OUT_DIR: ${{ env.OUT_DIR }}
          STORY_JSON_WRAPPER: ${{ env.STORY_JSON_WRAPPER }}

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
